/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_EXAMPLE_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_EXAMPLE_KEYS_H_
#define APPS_EXAMPLE_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */



/** @} end of group KV_IDS */

#endif /* APPS_EXAMPLE_KEYS_H_ */

