/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_DNS_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_DNS_KEYS_H_
#define APPS_DNS_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    DNS_INFO1 = 33792,/**< key_id = 0x8400 = 33792
                          description = Key DNS_INFO1 description
                          status = alive
                          structure = PIN    */
    DNS_INFO2 = 33793,/**< key_id = 0x8401 = 33793
                          description = Key DNS_INFO2 description
                          status = alive
                          structure = PIN    */
    DNS_INFO3 = 33794,/**< key_id = 0x8402 = 33794
                          description = Key DNS_INFO3 description
                          status = alive
                          structure = PIN    */
    DNS_INFO4 = 33795,/**< key_id = 0x8403 = 33795
                          description = Key DNS_INFO4 description
                          status = alive
                          structure = PIN    */
    DNS_INFO5 = 33796,/**< key_id = 0x8404 = 33796
                          description = Key DNS_INFO5 description
                          status = alive
                          structure = PIN    */
    DNS_INFO6 = 33797,/**< key_id = 0x8405 = 33797
                          description = Key DNS_INFO6 description
                          status = alive
                          structure = PIN    */
} DNS_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_DNS_KEYS_H_ */

