/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_LCGMR_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_LCGMR_KEYS_H_
#define APPS_LCGMR_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    LCGMR_INFO = 34304,/**< key_id = 0x8600 = 34304
                           description = Key LCGMR_INFO description
                           status = alive
                           structure = UNDETERMINED_SIZE_STRING    */
} LCGMR_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_LCGMR_KEYS_H_ */

