/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_NETWORK_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_NETWORK_KEYS_H_
#define APPS_NETWORK_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    NETWORK_SOCKET_SILENCE = 7168,/**< key_id = 0x1C00 = 7168
                                       description = Key NETWORK_SOCKET_SILENCE description
                                       status = alive
                                       structure = uint16    */
} NETWORK_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_NETWORK_KEYS_H_ */

