/******************************************************************************
 * @brief    AUTOGENERATED SOFTWARE MODULES: APPS_SYSTEM_SW_MODULE_IDS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_SYSTEM_SW_MODULE_IDS_H_
#define APPS_SYSTEM_SW_MODULE_IDS_H_

/** @addtogroup SOFTWARE_MODULES
 * @{
 * */

/**
 *  Keyspace is divded:
 *  - 8-bit module id (256 modules)
 *    - module ids 0-127: Neul/Huawei
 *    - module ids 128-255: customer configurable
 *  - 8-bit per-module key (maximum of 256 keys) per module key values are managed within the module
 */
typedef enum {
    APPS_SW_MODULE_BASE = 0,          /**< module_id = 0x0000 = 0
                                           module_name = BASE
                                           module_description = Module BASE description    */
    APPS_SW_MODULE_LWIP_SUPPORT = 1,  /**< module_id = 0x0001 = 1
                                           module_name = LWIP_SUPPORT
                                           module_description = Module LWIP_SUPPORT description    */
    APPS_SW_MODULE_AT = 8,            /**< module_id = 0x0008 = 8
                                           module_name = AT
                                           module_description = Module AT description    */
    APPS_SW_MODULE_LOG = 12,          /**< module_id = 0x000C = 12
                                           module_name = LOG
                                           module_description = Module LOG description    */
    APPS_SW_MODULE_OTA = 20,          /**< module_id = 0x0014 = 20
                                           module_name = OTA
                                           module_description = Module OTA description    */
    APPS_SW_MODULE_UNUSED = 24,       /**< module_id = 0x0018 = 24
                                           module_name = UNUSED
                                           module_description = Module UNUSED description    */
    APPS_SW_MODULE_NETWORK = 28,      /**< module_id = 0x001C = 28
                                           module_name = NETWORK
                                           module_description = Module NETWORK description    */
} APPS_SYSTEM_SW_MODULE_IDS;


/** @} end of group SOFTWARE_MODULES */

#endif /* APPS_SYSTEM_SW_MODULE_IDS_H_ */

