/******************************************************************************
 * @brief    Error handling for neul Functions for Hi21XX
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef NEUL_ERROR_H_
#define NEUL_ERROR_H_

#include "neulfw.h"

/** @defgroup NEUL_ERROR Hi21XX NEUL Errors
 * Hi21XX Neul Errors
 * @ingroup COMMON_TYPES
 * @{
 * */


typedef enum {
    NEUL_RET_OK = 0,
    NEUL_RET_ERROR,
    NEUL_RET_ERROR_RPC,
    NEUL_RET_ERROR_IN_PARAMETERS,
    NEUL_RET_ILLEGAL_OPERATION,
    NEUL_RET_RETRY_LATER,
    NEUL_RET_RETRY_AFTER_DEEP_SLEEP,
    NEUL_RET_KEY_NOT_FOUND,
    NEUL_RET_FLOW_CONTROL,
    NEUL_RET_IN_PROGRESS,
    NEUL_RET_NO_NETWORK_SERVICE,
    NEUL_RET_INVALID_ENTRY,
    NEUL_RET_OUT_OF_RANGE,
    NEUL_RET_MEMORY_ERROR,
    NEUL_RET_DISABLED_OPERATION,
    NEUL_RET_NOT_POWER_ON,
    NEUL_RET_KV_FLASH_FULL,
    NEUL_RET_CID_ACTIVE,
    NEUL_RET_RADIO_TEST_STATE_ERROR,
    NEUL_RET_RADIOTEST_DISABLED,
    NEUL_RET_NONIP_UNCONFIG,
    NEUL_RET_NONIP_NOT_REGISTERED,
    NEUL_RET_SIM_PIN_REQUIRED,
    NEUL_RET_CID_NOT_DEFINED,
    NEUL_RET_CID_NOT_ACTIVE,
    NEUL_RET_CID_INVALID,
    NEUL_RET_DEACTIVE_LAST_ACTIVE_CID,
    NEUL_RET_IN_PROGRESS_BLOCK,
    NEUL_RET_ABORT_BY_USER,
    NEUL_RET_ABORT_BY_USER_FAILED ,
    NEUL_RET_DATA_SEQUENCE_REPEAT_ERROR,
    NEUL_RET_NO_COMMAND_TO_ABORT,
    NEUL_RET_COMMAND_UNABORTABLE,
    NEUL_RET_COMMAND_INTERRUPTED,
    NEUL_RET_PROTOCOL_FAMILY_UNMATCHING,
    NEUL_RET_KEY_WRONG_SIZE,
    NEUL_RET_KEY_TOO_BIG,
    NEUL_RET_CONFIGURATION_CONFLICTS,
    NEUL_RET_SMS_NO_CNMA_ACKNOWLEDGEMENT_EXPECTED,
    NEUL_RET_SIM_PUK_REQUIRED,
    NEUL_RET_SIM_PUK_BLOCKED,
    NEUL_RET_NOT_MIPI_MODULE,
    NEUL_RET_FILE_NOT_FOUND,
    NEUL_RET_CONDITIONS_OF_USE_NOT_SATISFIED,
    NEUL_RET_NOT_INITIALISED,
} NEUL_RET;

/** @} end of group NEUL_ERROR */

#endif /* NEUL_ERROR_H_ */
