/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_DTLS_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_DTLS_KEYS_H_
#define APPS_DTLS_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    DTLS_SECURE_SWT = 4096,                  /**< key_id = 0x1000 = 4096
                                                  description = Key DTLS_SECURE_SWT description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_PSK = 4097,                  /**< key_id = 0x1001 = 4097
                                                  description = Key DTLS_SECURE_PSK description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_PSKID = 4098,                /**< key_id = 0x1002 = 4098
                                                  description = Key DTLS_SECURE_PSKID description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_TIME = 4099,                 /**< key_id = 0x1003 = 4099
                                                  description = Key DTLS_SECURE_TIME description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_HANDSHAKE_TYPE = 4100,       /**< key_id = 0x1004 = 4100
                                                  description = Key DTLS_SECURE_HANDSHAKE_TYPE description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_PSKIV = 4101,                /**< key_id = 0x1005 = 4101
                                                  description = Key DTLS_SECURE_PSKIV description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_PASSWORD = 4102,             /**< key_id = 0x1006 = 4102
                                                  description = Key DTLS_SECURE_PASSWORD description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_SALT = 4103,                 /**< key_id = 0x1007 = 4103
                                                  description = Key DTLS_SECURE_SALT description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_OLD_PSK = 4104,              /**< key_id = 0x1008 = 4104
                                                  description = Key DTLS_SECURE_OLD_PSK description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_NEW_PSK = 4105,              /**< key_id = 0x1009 = 4105
                                                  description = Key DTLS_SECURE_NEW_PSK description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_CONFIGING = 4106,            /**< key_id = 0x100A = 4106
                                                  description = Key DTLS_SECURE_CONFIGING description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_NAT_TYPE = 4107,             /**< key_id = 0x100B = 4107
                                                  description = Key DTLS_SECURE_NAT_TYPE description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_NEW_PSKID = 4108,            /**< key_id = 0x100C = 4108
                                                  description = Key DTLS_SECURE_NEW_PSKID description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_SECURE_NEW_HANDSHAKE_TYPE = 4109,   /**< key_id = 0x100D = 4109
                                                  description = Key DTLS_SECURE_NEW_HANDSHAKE_TYPE description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_PSK = 4110,               /**< key_id = 0x100E = 4110
                                                  description = Key DTLS_BS_SECURE_PSK description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_NEW_PSK = 4111,           /**< key_id = 0x100F = 4111
                                                  description = Key DTLS_BS_SECURE_NEW_PSK description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_PSKID = 4112,             /**< key_id = 0x1010 = 4112
                                                  description = Key DTLS_BS_SECURE_PSKID description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_NEW_PSKID = 4113,         /**< key_id = 0x1011 = 4113
                                                  description = Key DTLS_BS_SECURE_NEW_PSKID description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_HANDSHAKE_TYPE = 4114,    /**< key_id = 0x1012 = 4114
                                                  description = Key DTLS_BS_SECURE_HANDSHAKE_TYPE description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_NEW_HANDSHAKE_TYPE = 4115,/**< key_id = 0x1013 = 4115
                                                  description = Key DTLS_BS_SECURE_NEW_HANDSHAKE_TYPE description
                                                  status = alive
                                                  structure = PIN    */
    DTLS_BS_SECURE_NAT_TYPE = 4116,          /**< key_id = 0x1014 = 4116
                                                  description = Key DTLS_BS_SECURE_NAT_TYPE description
                                                  status = alive
                                                  structure = PIN    */
} DTLS_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_DTLS_KEYS_H_ */

