/******************************************************************************
 * @brief    AUTOGENERATED SOFTWARE MODULES: APPS_RDK_SW_MODULE_IDS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_RDK_SW_MODULE_IDS_H_
#define APPS_RDK_SW_MODULE_IDS_H_

/** @addtogroup SOFTWARE_MODULES
 * @{
 * */

/**
 *  Keyspace is divded:
 *  - 8-bit module id (256 modules)
 *    - module ids 0-127: Neul/Huawei
 *    - module ids 128-255: customer configurable
 *  - 8-bit per-module key (maximum of 256 keys) per module key values are managed within the module
 */
typedef enum {
    APPS_SW_MODULE_DTLS = 16,  /**< module_id = 0x0010 = 16
                                    module_name = DTLS
                                    module_description = Module DTLS description    */
    APPS_SW_MODULE_LWM2M = 128,/**< module_id = 0x0080 = 128
                                    module_name = LWM2M
                                    module_description = Module LWM2M description    */
    APPS_SW_MODULE_DNS = 132,  /**< module_id = 0x0084 = 132
                                    module_name = DNS
                                    module_description = Module DNS description    */
} APPS_RDK_SW_MODULE_IDS;


/** @} end of group SOFTWARE_MODULES */

#endif /* APPS_RDK_SW_MODULE_IDS_H_ */

