/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_AT_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_AT_KEYS_H_
#define APPS_AT_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    AT_KEYID_ATCMD_UART_CONFIG_V1 = 2048,/**< key_id = 0x0800 = 2048
                                              description = Key AT_KEYID_ATCMD_UART_CONFIG description
                                              status = deprecated
                                              structure = at_uart_config_v1    */
    AT_KEYID_ATCMD_UART_CONFIG = 2049,   /**< key_id = 0x0801 = 2049
                                              description = Key AT_KEYID_ATCMD_UART_CONFIG description
                                              status = alive
                                              structure = at_uart_config    */
} AT_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_AT_KEYS_H_ */

