/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_OTA_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_OTA_KEYS_H_
#define APPS_OTA_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    OTA_KEYID_UPDATE_STATE = 5120, /**< key_id = 0x1400 = 5120
                                        description = Key OTA_KEYID_UPDATE_STATE description
                                        status = reserved
                                        structure = uint8    */
    OTA_KEYID_UPDATE_RESULT = 5121,/**< key_id = 0x1401 = 5121
                                        description = Key OTA_KEYID_UPDATE_RESULT description
                                        status = reserved
                                        structure = uint8    */
    OTA_KEYID_UPDATE_TOKEN = 5122, /**< key_id = 0x1402 = 5122
                                        description = Key OTA_KEYID_UPDATE_TOKEN description
                                        status = reserved
                                        structure = str_token    */
    OTA_KEYID_UPDATE_MODE = 5123,  /**< key_id = 0x1403 = 5123
                                        description = Key OTA_KEYID_UPDATE_MODE description
                                        status = reserved
                                        structure = uint8    */
} OTA_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_OTA_KEYS_H_ */

