#===============================================================================
# @brief    Scons make file
# Copyright (c) 2016 NEUL LIMITED
#===============================================================================

Import('env')
import os
from ModuleUtils import *
from EnvironmentUtils import NeulTargetConfig

components = [ NeulTargetConfig.get_application(env) ]

if NeulTargetConfig.get_build_type(env) == BuildType.DOXYGEN:
    mod = Module('app', env, components)
    products = mod.build(env)

else:
    # Build the required target 'application'
    products = [ SConscript(os.path.join(NeulTargetConfig.get_application(env), 'SConscript'), {'env': env }) ]

Return ('products')
