/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_LWM2M_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_LWM2M_KEYS_H_
#define APPS_LWM2M_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    NV_DATA_MODE = 32768,               /**< key_id = 0x8000 = 32768
                                             description = Key NV_DATA_MODE description
                                             status = alive
                                             structure = PIN    */
    LWM2M_BS_PARA = 32769,              /**< key_id = 0x8001 = 32769
                                             description = Key LWM2M_BS_PARA description
                                             status = alive
                                             structure = PIN    */
    LWM2M_BS_MODE = 32770,              /**< key_id = 0x8002 = 32770
                                             description = Key LWM2M_BS_MODE description
                                             status = alive
                                             structure = NEUL_LOG_LEVEL    */
    LWM2M_FOTA_IND = 32771,             /**< key_id = 0x8003 = 32771
                                             description = Key LWM2M_FOTA_IND description
                                             status = alive
                                             structure = PIN    */
    LWM2M_SELFCURE_REG = 32772,         /**< key_id = 0x8004 = 32772
                                             description = Key LWM2M_SELFCURE_REG description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_IPV4 = 32773,             /**< key_id = 0x8005 = 32773
                                             description = Key LWM2M_CDP_IPV4 description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_PORT = 32774,             /**< key_id = 0x8006 = 32774
                                             description = Key LWM2M_CDP_PORT description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_ID = 32775,               /**< key_id = 0x8007 = 32775
                                             description = Key LWM2M_CDP_ID description
                                             status = alive
                                             structure = PIN    */
    LWM2M_REG_SWT = 32776,              /**< key_id = 0x8008 = 32776
                                             description = Key LWM2M_REG_SWT description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_IP = 32777,               /**< key_id = 0x8009 = 32777
                                             description = Key LWM2M_CDP_IP description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CLINENT_HOLD_OFF_TIMER = 32778,/**< key_id = 0x800A = 32778
                                             description = Key LWM2M_CLINENT_HOLD_OFF_TIMER description
                                             status = alive
                                             structure = PIN    */
    LWM2M_BOOTSTRAP_SERVER_IP = 32779,  /**< key_id = 0x800B = 32779
                                             description = Key LWM2M_BOOTSTRAP_SERVER_IP description
                                             status = alive
                                             structure = PIN    */
    LWM2M_BOOTSTRAP_SERVER_PORT = 32780,/**< key_id = 0x800C = 32780
                                             description = Key LWM2M_BOOTSTRAP_SERVER_PORT description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_NEW_IP = 32781,           /**< key_id = 0x800D = 32781
                                             description = Key LWM2M_CDP_NEW_IP description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_NEW_PORT = 32782,         /**< key_id = 0x800E = 32782
                                             description = Key LWM2M_CDP_NEW_PORT description
                                             status = alive
                                             structure = PIN    */
    LWM2M_SHORT_SERVERID = 32783,       /**< key_id = 0x800F = 32783
                                             description = Key LWM2M_SHORT_SERVERID description
                                             status = alive
                                             structure = PIN    */
    LWM2M_REMOTE_CONFIG_FLAG = 32784,   /**< key_id = 0x8010 = 32784
                                             description = Key LWM2M_REMOTE_CONFIG_FLAG description
                                             status = alive
                                             structure = PIN    */
    LWM2M_CDP_DOMAIN = 32785,           /**< key_id = 0x8011 = 32785
                                             description = Key LWM2M_CDP_DOMAIN description
                                             status = alive
                                             structure = PIN    */
    LWM2M_ENABLE_FLAG = 32786,          /**< key_id = 0x8012 = 32786
                                             description = Key LWM2M_ENABLE_FLAG description
                                             status = alive
                                             structure = PIN    */
    LWM2M_TYPE_UPLOAD_RESULT = 32787,   /**< key_id = 0x8013 = 32787
                                             description = Key LWM2M_TYPE_UPLOAD_RESULT description
                                             status = alive
                                             structure = PIN    */
    LWM2M_NEW_MESSAGE_ID = 32788,       /**< key_id = 0x8014 = 32788
                                             description = Key LWM2M_NEW_MESSAGE_ID description
                                             status = alive
                                             structure = PIN    */
    LWM2M_LIFETIME_SWT = 32789,         /**< key_id = 0x8015 = 32789
                                             description = Key LWM2M_LIFETIME_SWT description
                                             status = alive
                                             structure = PIN    */
} LWM2M_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_LWM2M_KEYS_H_ */

