/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_LOG_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_LOG_KEYS_H_
#define APPS_LOG_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    LOG_KEYID_UART_TX_PIN = 3072, /**< key_id = 0x0C00 = 3072
                                       description = Key LOG_KEYID_UART_TX_PIN description
                                       status = deprecated
                                       structure = PIN    */
    LOG_KEYID_NXLOG_CONFIG = 3073,/**< key_id = 0x0C01 = 3073
                                       description = Key LOG_KEYID_NXLOG_CONFIG description
                                       status = alive
                                       structure = bool    */
    LOG_KEYID_LOG_LEVEL = 3074,   /**< key_id = 0x0C02 = 3074
                                       description = Key LOG_KEYID_LOG_LEVEL description
                                       status = alive
                                       structure = NEUL_LOG_LEVEL    */
} LOG_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_LOG_KEYS_H_ */

