/******************************************************************************
 * @brief    AUTOGENERATED KEY IDS: APPS_UNUSED_KEYS
 * Copyright (c) 2018 Huawei Technologies Co. Ltd
******************************************************************************/

#ifndef APPS_UNUSED_KEYS_H_
#define APPS_UNUSED_KEYS_H_

/** @addtogroup KV_IDS
 * @{
 * */

typedef enum {
    UNUSED_KEYID_RESERVED_1 = 6144,/**< key_id = 0x1800 = 6144
                                        description = Key UNUSED_KEYID_RESERVED_1 description
                                        status = reserved
                                        structure = UNDETERMINED_SIZE_BUFFER    */
    UNUSED_KEYID_RESERVED_2 = 6145,/**< key_id = 0x1801 = 6145
                                        description = Key UNUSED_KEYID_RESERVED_2 description
                                        status = reserved
                                        structure = UNDETERMINED_SIZE_BUFFER    */
} UNUSED_KV_IDS;


/** @} end of group KV_IDS */

#endif /* APPS_UNUSED_KEYS_H_ */

