#===============================================================================
# @brief    Scons make file
# Copyright (c) 2017 NEUL LIMITED
#===============================================================================

Import('env')
import os
from EnvironmentUtils import NeulTargetConfig, BuildType
from ModuleUtils import Module

core = NeulTargetConfig.get_build_core(env)
module = 'config_eflash'
source_files = []

# Export headers.
public_include_dirs = [ os.path.join(Dir('.').srcnode().abspath, core)]

if NeulTargetConfig.get_build_type(env) in [BuildType.SOURCE_PACKAGE, BuildType.DOXYGEN]:
    mod = Module(module, env,
                 sources = source_files,
                 public_inc_dirs = public_include_dirs,
                 additional_release_files = Glob(core, '*.json'),
                 private_inc_dirs = [] )
    product = mod.build(env)
    Return ('product')
else:
    for cp in public_include_dirs:
        env.Append(CPPPATH = [ cp ])
    Return ('source_files')